// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfzC7qWMt2DPUOxWfjnKzSf_vv-CL1_S0',
    appId: '1:90853832068:web:b4662e4b3567d3331dd9d1',
    messagingSenderId: '90853832068',
    projectId: 'jopsque-aa40c',
    authDomain: 'jopsque-aa40c.firebaseapp.com',
    storageBucket: 'jopsque-aa40c.appspot.com',
    measurementId: 'G-SGPWC49D53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_PXspmPbA_jwjtsuOjORz3LMexaOfNLc',
    appId: '1:90853832068:android:c21c7563c7159fe71dd9d1',
    messagingSenderId: '90853832068',
    projectId: 'jopsque-aa40c',
    storageBucket: 'jopsque-aa40c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu5ddmXXs9WmtUSPIIB4sweytlhZ--CLQ',
    appId: '1:90853832068:ios:586776b444a285f51dd9d1',
    messagingSenderId: '90853832068',
    projectId: 'jopsque-aa40c',
    storageBucket: 'jopsque-aa40c.appspot.com',
    iosClientId: '90853832068-r36kvn41ljb3cav6tcob8k8ulfjvvq3c.apps.googleusercontent.com',
    iosBundleId: 'com.example.findjop',
  );
}
